name:                cowbot
version:             0.1.0.0
github:              "stereoknife/cowbot-hs"
license:             BSD-2-Clause
author:              "nil"
maintainer:          "stereoknife@yikes.dog"
copyright:           "2020 nil"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/stereoknife/cowbot-hs#readme>

dependencies:
- base >= 4.7 && < 5
- emoji == 0.1.0.2
- discord-haskell == 1.8.0
- text == 1.2.4.0
- parser-combinators == 1.2.1
- unliftio == 0.2.13
- req == 3.6.0
- aeson >= 1.4.7 && < 1.5
- vector == 0.12.1.2
- unordered-containers == 0.2.10.0
- google-translate == 0.5
- http-client == 0.6.4.1
- http-client-tls == 0.3.5.3
- containers == 0.6.2.1
- random == 1.1
- transformers == 0.5.6.2
- mtl == 2.2.2
- free == 5.1.3
- polysemy == 1.3.0.0
- polysemy-zoo == 0.7.0.1

library:
  source-dirs: src

executables:
  cowbot-bin:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cowbot

tests:
  cowbot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cowbot

default-extensions:
- OverloadedStrings
- FlexibleContexts
- GeneralizedNewtypeDeriving
