name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Cache stack
      uses: actions/cache@v1
      env:
        cache-name: cache-stack
      with:
        path: .stack-work
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/stack.yaml') }}-${{ hashFiles('**/package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
      
    - uses: actions/setup-haskell@v1.1
      with:
        ghc-version: '8.8.4'
        enable-stack: true
        stack-version: 'latest'

    - name: Install ghc
      run: stack setup
      
    - name: Install dependencies
      run: stack build cowbot --only-dependencies
          
    - name: Build
      run: stack build cowbot

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        # Artifact name
        name: build
        # A file, directory or wildcard pattern that describes what to upload
        path: .stack-work/**/bin/cowbot-bin
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: warn
